package main

import (
	"bytes"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"golang.org/x/tools/go/packages"
)

func TestIsGenerated(t *testing.T) {
	tests := []struct {
		name     string
		content  string
		expected bool
	}{
		{
			name:     "generated file",
			content:  "// Code generated by something DO NOT EDIT\npackage main",
			expected: true,
		},
		{
			name:     "regular file",
			content:  "package main\n\nfunc main() {}",
			expected: false,
		},
		{
			name:     "non-generated with code generated text",
			content:  "package main\n// This code was generated for testing",
			expected: false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			tmpDir := t.TempDir()
			testFile := filepath.Join(tmpDir, "test.go")
			if err := os.WriteFile(testFile, []byte(tt.content), 0o600); err != nil {
				t.Fatalf("Failed to write test file: %v", err)
			}
			got := isGenerated(testFile)
			if got != tt.expected {
				t.Errorf("isGenerated(%q) = %v, want %v", tt.name, got, tt.expected)
			}
		})
	}
}

func TestIsCgo(t *testing.T) {
	tests := []struct {
		name     string
		content  string
		expected bool
	}{
		{
			name:     "cgo file",
			content:  `package main\n\nimport "C"\n\nfunc main() {}`,
			expected: true,
		},
		{
			name:     "regular file",
			content:  "package main\n\nfunc main() {}",
			expected: false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			tmpDir := t.TempDir()
			testFile := filepath.Join(tmpDir, "test.go")
			if err := os.WriteFile(testFile, []byte(tt.content), 0o600); err != nil {
				t.Fatalf("Failed to write test file: %v", err)
			}
			got := isCgo(testFile)
			if got != tt.expected {
				t.Errorf("isCgo(%q) = %v, want %v", tt.name, got, tt.expected)
			}
		})
	}
}

func TestPromptUser(t *testing.T) {
	tests := []struct {
		name       string
		input      string
		expected   bool
		removeMode bool
	}{
		{
			name:       "default enter",
			input:      "\n",
			expected:   true,
			removeMode: false,
		},
		{
			name:       "comment short",
			input:      "c\n",
			expected:   true,
			removeMode: false,
		},
		{
			name:       "comment full",
			input:      "comment\n",
			expected:   true,
			removeMode: false,
		},
		{
			name:       "remove short",
			input:      "r\n",
			expected:   true,
			removeMode: true,
		},
		{
			name:       "remove full",
			input:      "remove\n",
			expected:   true,
			removeMode: true,
		},
		{
			name:       "ignore",
			input:      "i\n",
			expected:   false,
			removeMode: false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			oldStdin := os.Stdin
			oldRemoveMode := removeMode
			defer func() {
				os.Stdin = oldStdin
				removeMode = oldRemoveMode
			}()

			r, w, err := os.Pipe()
			if err != nil {
				t.Fatalf("Failed to create pipe: %v", err)
			}
			os.Stdin = r

			go func() {
				w.WriteString(tt.input)
				w.Close()
			}()

			removeMode = tt.removeMode
			target := Target{Identifier: "test", File: "test.go", Line: 1}
			got := promptUser(target)

			if got != tt.expected {
				t.Errorf("promptUser() = %v, want %v", got, tt.expected)
			}
		})
	}
}

func TestProcessTargets(t *testing.T) {
	oldDryRun := dryRun
	oldRemoveMode := removeMode
	oldInteractive := interactive
	defer func() {
		dryRun = oldDryRun
		removeMode = oldRemoveMode
		interactive = oldInteractive
	}()

	dryRun = true
	removeMode = false
	interactive = false

	tmpDir := t.TempDir()
	testFile := filepath.Join(tmpDir, "test.go")
	src := `package main

import "fmt"

func helper() {}

func main() {
	fmt.Println("hello")
}
`
	if err := os.WriteFile(testFile, []byte(src), 0o600); err != nil {
		t.Fatalf("Failed to write test file: %v", err)
	}

	targets := []Target{
		{File: testFile, Line: 4, Identifier: "helper", Kind: TargetDecl},
	}

	changed := processTargets(targets)
	if changed != 0 {
		t.Errorf("processTargets() in dry-run should return 0, got %d", changed)
	}
}

func TestProcessTargetsEdgeCases(t *testing.T) {
	oldDryRun := dryRun
	oldRemoveMode := removeMode
	oldInteractive := interactive
	defer func() {
		dryRun = oldDryRun
		removeMode = oldRemoveMode
		interactive = oldInteractive
	}()

	dryRun = true
	removeMode = false
	interactive = false

	// Test with empty targets first
	changed := processTargets([]Target{})
	if changed != 0 {
		t.Errorf("processTargets() should return 0 for empty targets, got %d", changed)
	}

	tests := []struct {
		name        string
		targets     []Target
		expectPanic bool
	}{
		{
			name: "skip exported identifier",
			targets: []Target{
				{File: "test.go", Line: 1, Identifier: "ExportedFunc", Kind: TargetDecl},
			},
		},
		{
			name: "skip generated file",
			targets: []Target{
				{File: "test.go", Line: 1, Identifier: "foo", Kind: TargetDecl},
			},
		},
		{
			name: "skip cgo file",
			targets: []Target{
				{File: "test.go", Line: 1, Identifier: "foo", Kind: TargetDecl},
			},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			tmpDir := t.TempDir()
			testFile := filepath.Join(tmpDir, "test.go")

			var src string
			switch tt.name {
			case "skip generated file":
				src = "// Code generated by something DO NOT EDIT\npackage main\nvar foo = 1\n"
			case "skip cgo file":
				src = `package main

import "C"

var foo = 1
`
			default:
				src = "package main\nvar foo = 1\n"
			}

			if err := os.WriteFile(testFile, []byte(src), 0o600); err != nil {
				t.Fatalf("Failed to write test file: %v", err)
			}
			tt.targets[0].File = testFile

			changed := processTargets(tt.targets)
			if changed != 0 {
				t.Errorf("processTargets() should return 0 for edge cases, got %d", changed)
			}
		})
	}
}

func TestExtractTargets(t *testing.T) {
	pkgs := []*packages.Package{
		{
			Errors: []packages.Error{
				{Pos: "main.go:5:2", Msg: "\"fmt\" imported and not used"},
				{Pos: "main.go:10:5", Msg: "x declared and not used"},
				{Pos: "main.go:15:6", Msg: "helper declared and not used"},
				{Pos: "main.go:20:1", Msg: "invalid syntax"}, // Should be ignored
			},
		},
	}

	targets := extractTargets(pkgs)

	if len(targets) != 3 {
		t.Fatalf("Expected 3 targets, got %d", len(targets))
	}

	expected := []Target{
		{File: "main.go", Line: 5, Identifier: "", Kind: TargetImport},
		{File: "main.go", Line: 10, Identifier: "x", Kind: TargetDecl},
		{File: "main.go", Line: 15, Identifier: "helper", Kind: TargetDecl},
	}

	for i, tgt := range expected {
		if targets[i].File != tgt.File || targets[i].Line != tgt.Line ||
			targets[i].Identifier != tgt.Identifier ||
			targets[i].Kind != tgt.Kind {
			t.Errorf("Target %d mismatch. Expected %+v, got %+v", i, tgt, targets[i])
		}
	}
}

func TestExtractTargetsEdgeCases(t *testing.T) {
	tests := []struct {
		name     string
		pkgs     []*packages.Package
		expected int
	}{
		{
			name: "deduplicate identical errors",
			pkgs: []*packages.Package{
				{
					Errors: []packages.Error{
						{Pos: "main.go:5:2", Msg: "\"fmt\" imported and not used"},
						{Pos: "main.go:5:2", Msg: "\"fmt\" imported and not used"},
					},
				},
			},
			expected: 1,
		},
		{
			name: "invalid position format",
			pkgs: []*packages.Package{
				{
					Errors: []packages.Error{
						{Msg: "some error without position"},
					},
				},
			},
			expected: 0,
		},
		{
			name: "unsupported error message",
			pkgs: []*packages.Package{
				{
					Errors: []packages.Error{
						{Pos: "main.go:5", Msg: "undefined function foo"},
					},
				},
			},
			expected: 0,
		},
		{
			name:     "empty packages",
			pkgs:     []*packages.Package{},
			expected: 0,
		},
		{
			name: "package with no errors",
			pkgs: []*packages.Package{
				{
					Errors: []packages.Error{},
				},
			},
			expected: 0,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			targets := extractTargets(tt.pkgs)
			if len(targets) != tt.expected {
				t.Errorf("extractTargets() returned %d targets, want %d", len(targets), tt.expected)
			}
		})
	}
}

func TestApplyRewrite(t *testing.T) {
	tests := []struct {
		name       string
		src        string
		target     Target
		expected   string
		isModified bool
	}{
		{
			name:       "Unused Import",
			src:        "package main\n\nimport \"fmt\"\n\nfunc main() {}",
			target:     Target{File: "test.go", Line: 3, Kind: TargetImport},
			expected:   "package main\n\nfunc main() {}\n",
			isModified: true,
		},
		{
			name:       "Unused Grouped Import",
			src:        "package main\n\nimport (\n\t\"fmt\"\n\t\"os\"\n)\n\nfunc main() {\n\t_ = os.Args\n}",
			target:     Target{File: "test.go", Line: 4, Kind: TargetImport},
			expected:   "package main\n\nimport (\n\t\"os\"\n)\n\nfunc main() {\n\t_ = os.Args\n}\n",
			isModified: true,
		},
		{
			name:       "Cleanup Empty Import Block",
			src:        "package main\n\nimport (\n\t\"fmt\"\n)\n\nfunc main() {}",
			target:     Target{File: "test.go", Line: 4, Kind: TargetImport},
			expected:   "package main\n\nfunc main() {}\n",
			isModified: true,
		},
		{
			name:       "Unused Variable",
			src:        "package main\n\nfunc main() {\n\tvar x = 1\n}",
			target:     Target{File: "test.go", Line: 4, Identifier: "x", Kind: TargetDecl},
			expected:   "package main\n\nfunc main() {\n\n}\n",
			isModified: true,
		},
		{
			name:       "Unused Constant",
			src:        "package main\n\nfunc main() {\n\tconst x = 1\n}",
			target:     Target{File: "test.go", Line: 4, Identifier: "x", Kind: TargetDecl},
			expected:   "package main\n\nfunc main() {\n\n}\n",
			isModified: true,
		},
		{
			name:       "Unused Grouped Variable",
			src:        "package main\n\nvar (\n\ta = 1\n\tb = 2\n)\n\nfunc main() {\n\t_ = b\n}",
			target:     Target{File: "test.go", Line: 4, Identifier: "a", Kind: TargetDecl},
			expected:   "package main\n\nvar (\n\tb = 2\n)\n\nfunc main() {\n\t_ = b\n}\n",
			isModified: true,
		},
		{
			name:       "Cleanup Empty Var Block",
			src:        "package main\n\nvar (\n\ta = 1\n)\n\nfunc main() {}",
			target:     Target{File: "test.go", Line: 4, Identifier: "a", Kind: TargetDecl},
			expected:   "package main\n\nfunc main() {}\n",
			isModified: true,
		},
		{
			name:       "Unused Variable in Multi Assignment",
			src:        "package main\n\nfunc main() {\n\tvar a, b = 1, 2\n\t_ = b\n}",
			target:     Target{File: "test.go", Line: 4, Identifier: "a", Kind: TargetDecl},
			expected:   "package main\n\nfunc main() {\n\tvar b = 2\n\t_ = b\n}\n",
			isModified: true,
		},
		{
			name:       "Unused Variable in Multi-Return Call",
			src:        "package main\n\nfunc foo() (int, int) { return 1, 2 }\n\nfunc main() {\n\tvar a, b = foo()\n\t_ = b\n}",
			target:     Target{File: "test.go", Line: 6, Identifier: "a", Kind: TargetDecl},
			expected:   "package main\n\nfunc foo() (int, int) { return 1, 2 }\n\nfunc main() {\n\tvar _, b = foo()\n\t_ = b\n}\n",
			isModified: true,
		},
		{
			name:       "Unused Short Assignment (Replace with _)",
			src:        "package main\n\nfunc foo() (int, int) { return 1, 2 }\n\nfunc main() {\n\ta, b := foo()\n\t_ = b\n}",
			target:     Target{File: "test.go", Line: 6, Identifier: "a", Kind: TargetDecl},
			expected:   "package main\n\nfunc foo() (int, int) { return 1, 2 }\n\nfunc main() {\n\t_, b := foo()\n\t_ = b\n}\n",
			isModified: true,
		},
		{
			name:       "Unused Function",
			src:        "package main\n\nfunc helper() {}\n\nfunc main() {}",
			target:     Target{File: "test.go", Line: 3, Identifier: "helper", Kind: TargetDecl},
			expected:   "package main\n\nfunc main() {}\n",
			isModified: true,
		},
		{
			name:       "Unused Type",
			src:        "package main\n\ntype Foo struct{}\n\nfunc main() {}",
			target:     Target{File: "test.go", Line: 3, Identifier: "Foo", Kind: TargetDecl},
			expected:   "package main\n\nfunc main() {}\n",
			isModified: true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			fset := token.NewFileSet()
			f, err := parser.ParseFile(fset, "test.go", tt.src, parser.ParseComments)
			if err != nil {
				t.Fatalf("Failed to parse src: %v", err)
			}

			modified := applyRewrite(fset, f, tt.target)
			if modified != tt.isModified {
				t.Errorf("Expected modified=%v, got %v", tt.isModified, modified)
			}

			var buf bytes.Buffer
			if err := format.Node(&buf, fset, f); err != nil {
				t.Fatalf("Failed to format node: %v", err)
			}

			// Normalize newlines for strict comparison
			got := strings.ReplaceAll(buf.String(), "\r\n", "\n")
			expected := strings.ReplaceAll(tt.expected, "\r\n", "\n")

			if got != expected {
				t.Errorf("Rewrite mismatch.\nExpected:\n%s\nGot:\n%s", expected, got)
			}
		})
	}
}

func TestApplyCommentText(t *testing.T) {
	tests := []struct {
		name       string
		src        string
		target     Target
		expected   string
		isModified bool
	}{
		{
			name:       "Comment Entire Function",
			src:        "package main\n\nfunc helper() {\n\tprintln(\"test\")\n}\n\nfunc main() {}",
			target:     Target{File: "test.go", Line: 3, Identifier: "helper", Kind: TargetDecl},
			expected:   "package main\n\n// func helper() {\n// \tprintln(\"test\")\n// }\n\nfunc main() {}",
			isModified: true,
		},
		{
			name:   "Fallback on Shared Variable Declaration",
			src:    "package main\n\nfunc main() {\n\tvar a, b = 1, 2\n\t_ = b\n}",
			target: Target{File: "test.go", Line: 4, Identifier: "a", Kind: TargetDecl},
			// Expect `a` to be removed, not commented, leaving `var b = 2`
			expected:   "package main\n\nfunc main() {\n\tvar b = 2\n\t_ = b\n}\n",
			isModified: true,
		},
		{
			name:   "Fallback on Short Assignment",
			src:    "package main\n\nfunc foo() (int, int) { return 1, 2 }\n\nfunc main() {\n\ta, b := foo()\n\t_ = b\n}",
			target: Target{File: "test.go", Line: 6, Identifier: "a", Kind: TargetDecl},
			// Expect `a` to be replaced with `_`, not commented
			expected:   "package main\n\nfunc foo() (int, int) { return 1, 2 }\n\nfunc main() {\n\t_, b := foo()\n\t_ = b\n}\n",
			isModified: true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			tmpDir := t.TempDir()
			testFile := filepath.Join(tmpDir, "test.go")

			if err := os.WriteFile(testFile, []byte(tt.src), 0o600); err != nil {
				t.Fatalf("Failed to write temp file: %v", err)
			}

			fset := token.NewFileSet()
			f, err := parser.ParseFile(fset, testFile, nil, parser.ParseComments)
			if err != nil {
				t.Fatalf("Failed to parse temp file: %v", err)
			}

			// Point the target to our dynamically generated temp file path
			target := tt.target
			target.File = testFile

			// Ensure dryRun is strictly false for the test to write to our temp file
			dryRun = false

			modified := applyCommentText(testFile, fset, f, target)
			if modified != tt.isModified {
				t.Errorf("Expected applyCommentText to return %v, got %v", tt.isModified, modified)
			}

			content, err := os.ReadFile(testFile)
			if err != nil {
				t.Fatalf("Failed to read modified temp file: %v", err)
			}

			got := strings.ReplaceAll(string(content), "\r\n", "\n")
			expected := strings.ReplaceAll(tt.expected, "\r\n", "\n")

			if got != expected {
				t.Errorf("CommentText mismatch.\nExpected:\n%s\nGot:\n%s", expected, got)
			}
		})
	}
}

func TestProcessTargetsRemoveMode(t *testing.T) {
	oldDryRun := dryRun
	oldRemoveMode := removeMode
	oldInteractive := interactive
	defer func() {
		dryRun = oldDryRun
		removeMode = oldRemoveMode
		interactive = oldInteractive
	}()

	// Test removeMode with actual file modification
	tmpDir := t.TempDir()
	testFile := filepath.Join(tmpDir, "test.go")
	src := `package main

import "fmt"

func main() {
	fmt.Println("hello")
}
`
	if err := os.WriteFile(testFile, []byte(src), 0o600); err != nil {
		t.Fatalf("Failed to write test file: %v", err)
	}

	dryRun = false
	removeMode = true
	interactive = false

	targets := []Target{
		{File: testFile, Line: 3, Identifier: "fmt", Kind: TargetImport},
	}

	changed := processTargets(targets)
	if changed != 1 {
		t.Errorf("processTargets() should return 1 for modified file, got %d", changed)
	}

	// Verify the file was modified
	content, err := os.ReadFile(testFile)
	if err != nil {
		t.Fatalf("Failed to read modified file: %v", err)
	}
	if strings.Contains(string(content), "import \"fmt\"") {
		t.Error("Import should have been removed")
	}
}

func TestProcessTargetsParseError(t *testing.T) {
	oldDryRun := dryRun
	oldRemoveMode := removeMode
	oldInteractive := interactive
	defer func() {
		dryRun = oldDryRun
		removeMode = oldRemoveMode
		interactive = oldInteractive
	}()

	dryRun = true
	removeMode = false
	interactive = false

	tmpDir := t.TempDir()
	testFile := filepath.Join(tmpDir, "test.go")

	// Write invalid Go code
	if err := os.WriteFile(testFile, []byte("package main invalid"), 0o600); err != nil {
		t.Fatalf("Failed to write test file: %v", err)
	}

	targets := []Target{
		{File: testFile, Line: 1, Identifier: "foo", Kind: TargetDecl},
	}

	changed := processTargets(targets)
	if changed != 0 {
		t.Errorf("processTargets() should return 0 for unparseable file, got %d", changed)
	}
}

func TestApplyCommentTextFallback(t *testing.T) {
	oldDryRun := dryRun
	defer func() { dryRun = oldDryRun }()

	dryRun = true

	tmpDir := t.TempDir()
	testFile := filepath.Join(tmpDir, "test.go")

	// This code won't be found by AST lookup - will trigger fallback
	src := `package main

func main() {
	a, b := foo()
	_ = b
}
func foo() (int, int) { return 1, 2 }
`
	if err := os.WriteFile(testFile, []byte(src), 0o600); err != nil {
		t.Fatalf("Failed to write test file: %v", err)
	}

	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, testFile, nil, parser.ParseComments)
	if err != nil {
		t.Fatalf("Failed to parse file: %v", err)
	}

	// Target a line that doesn't exist in AST - will trigger fallback
	target := Target{File: testFile, Line: 999, Identifier: "nonexistent", Kind: TargetDecl}

	modified := applyCommentText(testFile, fset, f, target)
	// Should return false since nothing was modified
	if modified {
		t.Error("Expected modified to be false for nonexistent target")
	}
}

func TestApplyCommentTextFallbackWithDryRun(t *testing.T) {
	oldDryRun := dryRun
	defer func() { dryRun = oldDryRun }()

	dryRun = true

	tmpDir := t.TempDir()
	testFile := filepath.Join(tmpDir, "test.go")

	// Short assignment - will trigger fallback in normal path too
	src := `package main

func main() {
	a, b := foo()
	_ = b
}
func foo() (int, int) { return 1, 2 }
`
	if err := os.WriteFile(testFile, []byte(src), 0o600); err != nil {
		t.Fatalf("Failed to write test file: %v", err)
	}

	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, testFile, nil, parser.ParseComments)
	if err != nil {
		t.Fatalf("Failed to parse file: %v", err)
	}

	// Target 'a' in short assignment - will fallback to rewrite
	target := Target{File: testFile, Line: 4, Identifier: "a", Kind: TargetDecl}

	modified := applyCommentText(testFile, fset, f, target)
	// In dryRun mode with fallback, should return modified=true but not write
	if !modified {
		t.Error("Expected modified to be true for short assignment fallback")
	}

	// Verify file was NOT modified (dryRun)
	content, _ := os.ReadFile(testFile)
	if !strings.Contains(string(content), "a, b :=") {
		t.Error("File should not have been modified in dryRun mode")
	}
}

func TestIsGeneratedEdgeCases(t *testing.T) {
	tests := []struct {
		name     string
		content  string
		expected bool
	}{
		{
			name:     "empty file",
			content:  "",
			expected: false,
		},
		{
			name:     "short file under 1000 chars",
			content:  "package main\nvar x = 1\n",
			expected: false,
		},
		{
			name:     "DO NOT EDIT without Code generated",
			content:  "package main\n// DO NOT EDIT\n",
			expected: false,
		},
		{
			name:     "Code generated without DO NOT EDIT",
			content:  "package main\n// Code generated by something\n",
			expected: false,
		},
		{
			name:     "both markers present",
			content:  "// Code generated by something DO NOT EDIT\npackage main\n",
			expected: true,
		},
		{
			name:     "truncated content at 1000 chars",
			content:  strings.Repeat("x", 500) + "Code generated" + strings.Repeat("y", 500),
			expected: false,
		},
		{
			name:     "truncated content with both markers at 1000",
			content:  strings.Repeat("x", 500) + "Code generatedDO NOT EDIT" + strings.Repeat("y", 500),
			expected: true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			tmpDir := t.TempDir()
			testFile := filepath.Join(tmpDir, "test.go")
			if err := os.WriteFile(testFile, []byte(tt.content), 0o600); err != nil {
				t.Fatalf("Failed to write test file: %v", err)
			}
			got := isGenerated(testFile)
			if got != tt.expected {
				t.Errorf("isGenerated(%q) = %v, want %v", tt.name, got, tt.expected)
			}
		})
	}

	// Test file read error
	got := isGenerated("/nonexistent/path/to/file.go")
	if got != false {
		t.Errorf("isGenerated for nonexistent file = %v, want false", got)
	}
}

func TestIsCgoEdgeCases(t *testing.T) {
	// Test file read error - use a non-existent file
	got := isCgo("/nonexistent/path/to/file.go")
	if got != false {
		t.Errorf("isCgo for nonexistent file = %v, want false", got)
	}
}

func TestProcessTargetsMultipleTargets(t *testing.T) {
	oldDryRun := dryRun
	oldRemoveMode := removeMode
	oldInteractive := interactive
	defer func() {
		dryRun = oldDryRun
		removeMode = oldRemoveMode
		interactive = oldInteractive
	}()

	dryRun = true
	removeMode = false
	interactive = false

	tmpDir := t.TempDir()
	testFile := filepath.Join(tmpDir, "test.go")
	src := `package main

import "fmt"
import "os"

func helper() {}

func main() {
	fmt.Println("hello")
	_ = os.Args
}
`
	if err := os.WriteFile(testFile, []byte(src), 0o600); err != nil {
		t.Fatalf("Failed to write test file: %v", err)
	}

	targets := []Target{
		{File: testFile, Line: 3, Identifier: "helper", Kind: TargetDecl},
		{File: testFile, Line: 4, Identifier: "fmt", Kind: TargetImport},
		{File: testFile, Line: 5, Identifier: "os", Kind: TargetImport},
	}

	changed := processTargets(targets)
	if changed != 0 {
		t.Errorf("processTargets() in dry-run should return 0, got %d", changed)
	}
}

func TestProcessTargetsFormatError(t *testing.T) {
	oldDryRun := dryRun
	oldRemoveMode := removeMode
	oldInteractive := interactive
	defer func() {
		dryRun = oldDryRun
		removeMode = oldRemoveMode
		interactive = oldInteractive
	}()

	dryRun = false
	removeMode = true
	interactive = false

	tmpDir := t.TempDir()
	testFile := filepath.Join(tmpDir, "test.go")

	// Write a file that can't be formatted properly after our changes
	src := `package main

var foo = 1
`
	if err := os.WriteFile(testFile, []byte(src), 0o600); err != nil {
		t.Fatalf("Failed to write test file: %v", err)
	}

	// Target a const which doesn't exist - will cause applyRewrite to return false
	targets := []Target{
		{File: testFile, Line: 3, Identifier: "nonexistent", Kind: TargetDecl},
	}

	changed := processTargets(targets)
	// Should not crash, just return 0 or 1 depending on whether anything was modified
	_ = changed
}
